# Generated by Django 3.2.9 on 2021-11-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='discription',
            new_name='description',
        ),
    ]
